 jcb({ "birdList":[
        { name: 'Ashy Swallow Shrike or ashy wood swallow', id: 50 },
        { name: 'Asian Koel', id: 58 },
        { name: 'Baya Weaver Bird', id: 59 },
        { name: 'Beautiful Sibia', id: 22 },
        { name: 'Blackwinged Kite ', id: 51 },
        { name: 'Blue Pitta', id: 33 },
        { name: 'Brahminy Kite ', id: 60 },
        { name: 'Brown Parrotbill', id: 30 },
        { name: 'Cattle Egret', id: 52 },
        { name: 'Common Indian Nightjar', id: 61 },
        { name: 'Common or Barn Swallow', id: 62 },
        { name: 'Common Rosefinch', id: 31 },
        { name: 'Common Sandpiper', id: 63 },
        { name: 'Crested Serpent Eagle', id: 64 },
        { name: 'Crested Tree Swift', id: 65 },
        { name: 'Crimson sunbird', id: 32 },
        { name: 'Crow Pheasant or Coucal', id: 66 },
        { name: 'Dollarbird', id: 29 },
        { name: 'Fire-fronted Serin', id: 36 },
        { name: 'Fire-tailed Myzornis', id: 41 },
        { name: 'Fire-tailed Sunbird', id: 2 },
        { name: 'Forest Wagtail', id: 67 },
        { name: 'Great Barbet', id: 9 },
        { name: 'Grey Heron', id: 42 },
        { name: 'Grey Junglefowl', id: 68 },
        { name: 'Grey Wagtail', id: 69 },
        { name: 'Grey-headed Canary Flycatcher', id: 37 },
        { name: 'Grey-headed Starling', id: 15 },
        { name: 'Greylag Goose', id: 38 },
        { name: 'Heart-spotted Woodpecker', id: 70 },
        { name: 'Himalayan Cutia', id: 6 },
        { name: 'Himalayan Woodpecker', id: 8 },
        { name: 'Hoary-throated Barwing', id: 18 },
        { name: 'Hoopoe', id: 71 },
        { name: 'Ibis', id: 101, by: 'Namrata H' },
        { name: 'Ibisbill', id: 27 },
        { name: 'Indian Roller', id: 102, by: 'Namrata H' },
        { name: 'Indian Silverbill or White-throated Munia', id: 72 },
        { name: 'Indian Treepie', id: 53 },
        { name: 'Large Pied Wagtail', id: 54 },
        { name: 'Lesser Adjutant Stork', id: 43 },
        { name: 'Lesser Golden-backed Woodpecker', id: 55 },
        { name: 'Little Cormorant', id: 44 },
        { name: 'Little Grebe or Dabchick', id: 56 },
        { name: 'Long-tailed Broadbill', id: 21 },
        { name: 'Malabar Crested Lark', id: 73 },
        { name: 'Malabar Whistling - Thrush', id: 74 },
        { name: 'Maroon Oriole', id: 10 },
        { name: 'Mendels Leaf Warbler', id: 28 },
        { name: 'Mistle Thrush', id: 7 },
        { name: 'Openbill Stork', id: 45 },
        { name: 'Orange bellied leafbird', id: 13 },
        { name: 'Orange-flanked Bush Robin', id: 16 },
        { name: 'Painted Stork', id: 103, by: 'Namrata H' },
        { name: 'Pariah Kite or Black kite', id: 46 },
        { name: 'Peacock', id: 104, by: 'Namrata H' },
        { name: 'Pied Kingfisher', id: 75 },
        { name: 'Pigmy Woodpecker', id: 47 },
        { name: 'Plumbeous Water Redstart', id: 25 },
        { name: 'Pond Heron', id: 105, by: 'Namrata H' },
        { name: 'Purple Moorhen', id: 76 },
        { name: 'Red Spurfowl', id: 48 },
        { name: 'Red Whiskered Bulbul', id: 106, by: 'Namrata H' },
        { name: 'Red-headed Bullfinch', id: 11 },
        { name: 'Red-rumped swallow', id: 77 },
        { name: 'Redwattled Lapwing', id: 78 },
        { name: 'River Tern', id: 79 },
        { name: 'Rofous Sibia', id: 40 },
        { name: 'Rufous-capped Babbler', id: 3 },
        { name: 'Scaly Laughingthrush', id: 34 },
        { name: 'Scarlet Minivet', id: 107, by: 'Namrata H' },
        { name: 'Shikra', id: 49 },
        { name: 'Sirkeer Malkoha', id: 39 },
        { name: 'Slender-billed Scimitar Babbler', id: 14 },
        { name: 'Small blue Kingfisher', id: 80 },
        { name: 'Spotted or Scaly breasted Munia', id: 81 },
        { name: 'Spotted Owlet', id: 82 },
        { name: 'Spot-winged Tit', id: 1 },
        { name: 'Steaked Laughing Thrush', id: 4 },
        { name: 'Stork-billed Kingfisher', id: 108  },
        { name: 'Tawny Fish Owl', id: 24 },
        { name: 'Tibetan Sandgrouse', id: 23 },
        { name: 'Tickells Brown Hornbill', id: 5 },
        { name: 'Tickells Fly Catcher', id: 109, by: 'Namrata H' },
        { name: 'Ultramarine Flycatcher', id: 19 },
        { name: 'Velvet-fronted Nuthatch', id: 83 },
        { name: 'Wagtail', id: 110, by: 'Namrata H' },
        { name: 'Wallcreeper', id: 35 },
        { name: 'Whiskered Yuhina', id: 26 },
        { name: 'White Wagtail', id: 57 },
        { name: 'white-breasted Kingfisher', id: 84 },
        { name: 'White-breasted Waterhen', id: 85 },
        { name: 'White-browed Fulvetta', id: 20 },
        { name: 'White-rumped Shama', id: 12 },
        { name: 'Wire-tailed Swallow', id: 86 },
        { name: 'Yellow-bellied Fantail', id: 17 }
      ]
 });